routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use App\Http\Controllers\CompaniesController;
use App\Http\Controllers\EmployeesController;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::group(['middleware' => ["auth"]],function(){

    Route::post("/updatestates",[CompaniesController::class, 'updateStates'])->name("updateStates");
    Route::get("/deleteImage/{id}",[CompaniesController::class, 'deleteImage'])->name("deleteImage");
    Route::resources([
        'companies' => CompaniesController::class,
        'employees' => EmployeesController::class,
    ]);
});
require __DIR__.'/auth.php';

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
    
    protected $fillable = [ "name","email","logo","website","address","country_id","state_id"];
}

app/Http/Controllers/CompaniesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Company;
use App\Models\Country;
use App\Models\State;

class CompaniesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::paginate(10);
        return view("companies.index",compact("companies"));
        
    }

    public function updateStates(Request $request){
        $data = $request->all();
        if(isset($data["country"])){
            $states = State::where("country_id",$data["country"])->get();
            return view("companies.states",compact('states'));
        }
        return false;
    }


    public function deleteImage($id){
        $company=Company::find($id);
        if(file_exists("storage/".$company->logo)){
            unlink("storage"."/".$company->logo);
            $company->logo = "";
            $company->update();
        }
        return redirect()->back();
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countries = Country::all();
        return view("companies.create",compact("countries"));        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,$id=null)
    {
        $data = $request->all();
        $name="";
        $rules =[
            'name' => 'required|regex:/^[\pL\s\-]+$/u',
            'email' => 'required|email',                        
            'logo' => 'image'
        ];

        $error_msg=[
            'name.required' => 'Company name is required',
            'name.regex'=>'Please enter valid company name',
            'url.required' => 'Enter valid URL ',
            'logo.image'=>'Upload Valid Image',
        ];

        $this->validate($request,$rules,$error_msg);

        if($id==null){
            if($request->hasFile("logo") ){
                $tmp_image = $request->file("logo");
                $name = $tmp_image->getClientOriginalName();
                $request->logo->storeAs('public', $name);                
                //print "<pre>"; print_r($data); die;
            }
            Company::create(["name"=>$data["name"], "email"=>$data["email"], "logo" => $name, 
            "website"=>$data["website"], "address" => $data["address"], "country_id"=>$data["country"], "state_id" =>$data["state"] ]) ;           
        }
       
        //
        return redirect()->route("companies.index");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company=Company::find($id);
        $countries = Country::all();
        $states = State::where('country_id',$company->country_id)->get();
        return view("companies.edit",compact("countries","company","states"));        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        $company = Company::findOrfail($id);
            if($company)
            {
                if($request->hasFile("logo")){
                    $tmp_image = $request->file("logo");
                    $name = $tmp_image->getClientOriginalName();
                    $request->logo->storeAs('public', $name);   
                    $company->logo=$name;             
                }
                $company->name=$data["name"];
                $company->email=$data["email"];
                $company->website=$data["website"];
                $company->address=$data["address"];
                $company->country_id=$data["country"];
                $company->state_id=$data["state"];
                $company->update();
            }

        return redirect()->route("companies.index");              
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Company::findOrfail($id);
        if($company){
            $company->delete();
        }
        return redirect()->route("companies.index");                          
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/companies/create.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create New Company') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    
                @if($errors->any())
                <div class="alert-danger py-4">
                    <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                    </ul>
                </div>
                @endif

                <form action="{{route('companies.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                <div class="form-group">
                    <label for="exampleInputName">Name</label>
                    <input type="text" name="name" class="form-control" id="exampleInputName" placeholder="Enter Name" value="{{old('name')}}">
                </div>

                <div class="form-group">
                    <label for="exampleInputName">Email</label>
                    <input type="email" name="email" class="form-control" id="exampleInputName" aria-describedby="emailHelp" placeholder="Enter Email" value="{{old('email')}}">
                </div>

                <div class="form-group">
                    <label for="exampleFormControlFile1">Logo</label>
                    <input type="file" name="logo" class="form-control-file" id="exampleFormControlFile1">
                </div>     
                
                <div class="form-group">
                    <label for="exampleInputName">Website</label>
                    <input type="text" name="website" class="form-control" id="exampleInputWebsite" placeholder="Enter Website" value="{{old('website')}}">
                </div>

                <div class="form-group">
                    <label for="exampleInputName">Address</label>
                    <input type="text" name="address" class="form-control" id="exampleInputAddress" aria-describedby="emailHelp" placeholder="Enter Address" value="{{old('Address')}}">
                </div>

                <div class="form-group">
                    <label for="exampleFormControlSelect1">Country</label>
                    <select name="country" class="form-control" id="country">
                        <option value="">Select</option>
                    @foreach($countries as $country)
                    <option value="{{$country->id}}">{{$country->name}}</option>
                    @endforeach
                    </select>
                </div>

                <div id="states">
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">State</label>
                        <select name="state" class="form-control" id="exampleFormControlSelect1">
                        <option value="">Select</option>                        
                        </select>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
                </form>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/companies/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Create New Company') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    
                <form action="{{route('companies.update',$company->id)}}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                <div class="form-group">
                    <label for="exampleInputName">Name</label>
                    <input type="text" name="name" class="form-control" id="exampleInputName" placeholder="Enter Name" value="{{$company->name}}">
                </div>

                <div class="form-group">
                    <label for="exampleInputName">Email</label>
                    <input type="email" name="email" class="form-control" id="exampleInputName" aria-describedby="emailHelp" placeholder="Enter Email" value="{{$company->email}}">
                </div>

                <div class="form-group">
                    <label for="exampleFormControlFile1">Logo</label>
                    <input type="file" name="logo" class="form-control-file" id="exampleFormControlFile1">
                    @if(isset($company->logo))
                    <img width="100px" src="{{ asset('storage/'.$company->logo) }}" alt="logo">
                    <a href="{{route('deleteImage',$company->id)}}">Delete</a>
                    @endif
                </div>     
                
                <div class="form-group">
                    <label for="exampleInputName">Website</label>
                    <input type="text" name="website" class="form-control" id="exampleInputWebsite" placeholder="Enter Website" value="{{$company->website}}">
                </div>

                <div class="form-group">
                    <label for="exampleInputName">Address</label>
                    <input type="text" name="address" class="form-control" id="exampleInputAddress" aria-describedby="emailHelp" placeholder="Enter Address" value="{{$company->address}}">
                </div>

                <div class="form-group">
                    <label for="exampleFormControlSelect1">Country</label>
                    <select name="country" class="form-control" id="country">
                        <option value="">Select</option>
                    @foreach($countries as $country)
                    <option value="{{$country->id}}" @if($company->country_id == $country->id) selected @endif>{{$country->name}}</option>
                    @endforeach
                    </select>
                </div>

                <div id="states">
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">State</label>
                        <select name="state" class="form-control" id="exampleFormControlSelect1">
                        <option value="">Select</option>    
                        @foreach($states as $state)
                        <option value="{{$country->id}}" @if($company->state_id == $state->id) selected @endif>{{$state->name}}</option>
                        @endforeach                                            
                        </select>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
                </form>

                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/companies/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('List') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <a href="{{route('companies.create')}}" class="btn btn-primary">Add New Company</a>
                <table class="table">
                    <thead>
                        <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Website</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                    @if(isset($companies))
                    @foreach($companies as $company)
                        <tr>
                        <td>{{$company->name}}</td>
                        <td>{{$company->email}}</td>
                        <td>{{$company->website}}</td> 
                        <td><a href="{{route('companies.edit',$company->id)}}" class="btn btn-primary">Edit</a></td>
                        <td><form action="{{route('companies.destroy',$company->id)}}" method="post">
                        <button type="submit" class="btn btn-danger">Delete</button>
                            @csrf @method("delete")
                        </form></td>
                        </tr>
                    @endforeach
                    @endif                                           
                    </tbody>
                </table>
                   {{ $companies->links() }}
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/companies/states.blade.php
<div class="form-group">
    <label for="exampleFormControlSelect1">State</label>
    <select name="state" class="form-control" id="exampleFormControlSelect1">
        <option value="">Select States</option>
    @foreach($states as $state)
    <option value="{{$state->id}}">{{$state->name}}</option>
    @endforeach
    </select>
</div>